#!/bin/python
import os
import sys
import subprocess
sys.path.append('/root/bin/blog')
import sioscockroach
import myvariables
from myvariables import *

sys.exit(sioscockroach.statusDB(execCmd,addr))
